title: "モノリスで構築するRails7 & React18のWebアプリケーション構築手順書"
summary: "Rails7とReact18を使ったWEBアプリケーションを構築するためのノウハウをまとめています"
topics: ["rails", "react", "tutorial"]
published: true # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - chapter1
  - chapter2
  - chapter5
  - chapter6
  - chapter7